version: "3.8"

services:
  zeek-monitor:
    image: zeek/zeek:latest
    container_name: zeek-mail-monitor
    network_mode: host                      # needed for packet capture
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ../../zeek-scripts:/scripts:ro
      - ../../output/live:/logs
      - ../../output/state:/state
    env_file:
      - ../../.env                          # optional; maintain SITE_ID/LINK_ID/etc.
    environment:
      SITE_ID: ${SITE_ID:-overseas}
      LINK_ID: ${LINK_ID:-overseas-hq-1}
      LAN_INTERFACE: ${LAN_INTERFACE:-eno1}
      TUNNEL_INTERFACE: ${TUNNEL_INTERFACE:-tap_tap}
      REPORT_INTERVAL: ${REPORT_INTERVAL:-30}
      MAIL_STATS_STATE_FILE: /state/mail_stats_state.tsv
      ZEEK_IFACE: ${ZEEK_IFACE:-eth0}
      FILTER: "${FILTER:-port 25 or port 465 or port 587 or port 1025 or port 2525 or port 110 or port 995 or port 143 or port 993 or port 3025 or port 3110 or port 3143 or port 3465 or port 3993 or port 3995}"
    command: >
      zeek -C -i ${ZEEK_IFACE:-eth0} -f "${FILTER}" /scripts/mail-activity-json.zeek
    restart: unless-stopped
