services:
  greenmail:
    image: greenmail/standalone:1.6.15
    restart: unless-stopped
    environment:
      GREENMAIL_OPTS: >-
        -Dgreenmail.setup.test.smtp
        -Dgreenmail.setup.test.pop3
        -Dgreenmail.hostname=0.0.0.0
        -Dgreenmail.users=demo:demo@localhost.local
        -Dgreenmail.auth.disabled
    ports:
      - "3025:3025"   # SMTP
      - "3110:3110"   # POP3
