services:
  greenmail:
    image: greenmail/standalone:2.0.1
    restart: unless-stopped
    environment:
      GREENMAIL_OPTS: >-
        -Dgreenmail.setup.test.all
        -Dgreenmail.hostname=0.0.0.0
        -Dgreenmail.users=demo:demo@localhost.local
        -Dgreenmail.auth.disabled
        -Dgreenmail.verbose
      JAVA_OPTS: >-
        -Djava.net.preferIPv4Stack=true
        -Xmx512m
    ports:
      - "3025:3025"   # SMTP
      - "3110:3110"   # POP3
      - "3143:3143"   # IMAP
      - "3465:3465"   # SMTPS
      - "3993:3993"   # IMAPS
      - "3995:3995"   # POP3S
      - "8280:8080"   # Web interface
