services:
  greenmail:
    image: greenmail/standalone:1.6.15
    restart: unless-stopped
    environment:
      GREENMAIL_OPTS: >-
        -Dgreenmail.setup=SMTP:3025,POP3:3110
        -Dgreenmail.hostname=0.0.0.0
        -Dgreenmail.users=demo:demo@local
        -Dgreenmail.start.tls=false
    ports:
      - "1025:3025"   # SMTP (mapped to localhost:1025)
      - "1110:3110"   # POP3 (mapped to localhost:1110)
